Test program syntax errors

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -78,3 +78,14 @@ if ! grep '^error: syntax error,' $d/out > /dev/null; then
     echo "Module system not detecting syntax errors in modules correctly" 1>&2
     exit 1
 fi
+
+if $VALGRIND ./jq -ner -L $d '%::wat' > $d/out 2>&1 ||
+   ! grep '^error: syntax error,' $d/out > /dev/null; then
+    echo "Syntax errors not detected?" 1>&2
+    exit 1
+fi
+if ! grep 'ERROR SUMMARY: 0 errors from 0 contexts' $d/out > /dev/null; then
+    echo "Memory errors when programs have syntax errors" 1>&2
+    cat $d/out
+    exit 1
+fi
